from .musicflamingo_analysis import (
    MusicFlamingoAnalysis,
    NODE_CLASS_MAPPINGS as _ANALYSIS_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as _ANALYSIS_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(_ANALYSIS_NODE_CLASS_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(_ANALYSIS_NODE_DISPLAY_NAME_MAPPINGS)

__all__ = [
    "MusicFlamingoAnalysis",
    "NODE_CLASS_MAPPINGS",
]

